hwi_oauth:
    firewall_names:        [secured_area]
    resource_owners:
        facebook:
            type:          facebook
            client_id:     '%env(FACEBOOK_APP_ID)%'
            client_secret: '%env(FACEBOOK_APP_SECRET)%'
            scope:         "email"
            options:
                display: popup #dialog is optimized for popup window
                auth_type: rerequest # Re-asking for Declined Permissions