security:
    encoders:
        Symfony\Component\Security\Core\User\UserInterface: bcrypt

    providers:
        in_memory:
            memory:
                users:
                    apidoc:
                        password: "$2y$13$YRl37cfrgWGXMlmFrmwXyuBd3c8MJA4.K7YglA6.0Oz.Zi6k8ooVi"

    firewalls:
        dev:
            pattern: "^/(_(profiler|wdt)|css|images|js)/"
            security: false

        apidoc:
            pattern: "^/api$"
            http_basic: true
            provider: in_memory

        main:
            pattern: "^/"
            anonymous: true

    access_control:
        - { path: "^/api$", roles: IS_AUTHENTICATED_FULLY }
