security:
    encoders:
        Symfony\Component\Security\Core\User\UserInterface: bcrypt
        App\Entity\Admin: bcrypt

    providers:
        in_memory:
            memory:
                users:
                    apidoc:
                        password: "$2y$13$YRl37cfrgWGXMlmFrmwXyuBd3c8MJA4.K7YglA6.0Oz.Zi6k8ooVi"
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: username

    firewalls:
        dev:
            pattern: "^/(_(profiler|wdt)|css|images|js)/"
            security: false

        apidoc:
            pattern: "^/api$"
            http_basic: true
            provider: in_memory

        admin:
            pattern: "^/admin"
            provider: admin_provider
            http_basic: true

        main:
            pattern: "^/"
            anonymous: true
            security: false

    access_control:
        - { path: "^/api$", roles: IS_AUTHENTICATED_FULLY }
        - { path: "^/admin", roles: ROLE_ADMIN }
        - { path: "^/", roles: IS_AUTHENTICATED_ANONYMOUS }
