security:
   encoders:
       App\Entity\User:
           algorithm: bcrypt

   providers:
        my_custom_hwi_provider:
            id: ib_user.oauth_user_provider
#        hwi:
#            id: hwi_oauth.user.provider

   firewalls:
       dev:
           pattern: ^/(_(profiler|wdt)|css|images|js)/
           security: false
       secured_area:
           pattern:    ^/
           oauth:
               resource_owners:
                   facebook:      /login_facebook
               login_path:        /login
               failure_path:      /login
               oauth_user_provider:
                   service: ib_user.oauth_user_provider
#                   service: hwi_oauth.user.provider.entity
           anonymous: ~
           logout:
               path:   /logout
               target: /

   access_control:
       - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/admin, roles: ROLE_ADMIN }
       - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

   role_hierarchy:
         ROLE_ADMIN: ROLE_USER
         ROLE_USER: ROLE_USER