language: php

matrix:
  fast_finish: true
  include:
    - php: '7.1'
      env: TARGET=phpcs
    - php: '7.1'
      env: TARGET=phpmd
    - php: '7.1'
      env: TARGET=phpunit

before_script:
    - composer self-update
    - composer install

script:
  - if [ "$TARGET" = "phpunit" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover; fi
