language: php

matrix:
  fast_finish: true
  include:
    - php: '7.1'

before_script:
    - composer self-update
    - composer install

script:
  - ./vendor/bin/phpcs ./src ./tests -p --encoding=utf-8 --extensions=php --standard=./vendor/escapestudios/symfony2-coding-standard/Symfony --exclude=Symfony.Commenting.License;
  - ./vendor/bin/phpunit --coverage-text -c phpunit.xml.dist;
