parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Command\CreateAdminCommand:
        arguments:
            - "@security.user_password_encoder.generic"
            - "@doctrine"
        tags:
            - { name: console.command }
